      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.PORT }}

          script: |
            set -e

            echo "============================"
            echo "Starting Deployment..."
            echo "============================"

            cd /var/www/elmenShop

            git fetch origin
            git reset --hard origin/Main

            FRONTEND="${{ steps.filter.outputs.frontend }}"
            BACKEND="${{ steps.filter.outputs.backend }}"

            echo "Frontend Changed: $FRONTEND"
            echo "Backend Changed: $BACKEND"

            ####################################################
            ## FRONTEND
            ####################################################

            if [ "$FRONTEND" = "true" ]; then

              echo "Building Frontend..."

              cd frontend

              npm ci

              npm run build

              cd ..

            fi

            ####################################################
            ## BACKEND
            ####################################################

            if [ "$BACKEND" = "true" ]; then

              echo "Installing Backend..."

              cd backend

              npm ci --omit=dev

              cd ..

              pm2 restart elmenshop --update-env

            fi

            echo "Checking Backend..."

            sleep 5

            curl http://localhost:5000/api/health

            pm2 save

            echo "Deployment Completed Successfully"